config/routes.rb
Rails.application.routes.draw do
  root to: 'cocktails#index'
  get 'pages/about'
  get 'pages/menu'
  resources :cocktails do
    resources :doses, only: [:new, :create]
  end
  resources :doses, only: [:destroy]
  resources :pages, only: [:about, :home] do
    collection do
      get 'about', to: 'pages#about', as: :about
    end
  end
end

 # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  mount_uploader :photo, PhotoUploader

  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  validates :name, uniqueness: true, presence: true
  validates :photo, presence: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates :cocktail_id, uniqueness: { scope: :ingredient_id }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses

  validates :name, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @cocktail = @dose.cocktail
    @dose.destroy
    redirect_to cocktail_path(@cocktail)
  end

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def menu
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
  def cocktail_image_path(cocktail)
    if cocktail.photo.blank?
      image_path('logo.png')
    else
      cl_image_path(cocktail.photo, height: 300, width: 400, crop: :fill)
    end
  end
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/cocktails/_banner.html.erb
<div class="banner">
  <div class="banner-content">
    <h1>Cocktails for all</h1>
    <p>Share your best recipes to the community</p>
    <%= link_to "Add a cocktail", new_cocktail_path, class: "btn btn-success" %>
  </div>
</div>

app/views/cocktails/_card.html.erb
<div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cocktail_image_path(cocktail) %>')">
  <div class="card-description">
    <p><%= link_to cocktail.name%></p>
  </div>
  <%= link_to "", cocktail_path(cocktail), class: "card-link" %>
</div>

app/views/cocktails/index.html.erb
<%= render 'layouts/navbar' %>
<%= render 'cocktails/banner' %>

<div class="container">
  <div class="row">
    <% @cocktails.each do |cocktail| %>
      <div class="col-xs-6 col-sm-4">
        <%= render 'cocktails/card', cocktail: cocktail %>
      </div>
    <% end %>
  </div>
</div>

</div>

<div class="footer_home">

  <div class="footer-copyright">
    </i><p>MVP made at Le Wagon</p>
  </div>
</div>

app/views/cocktails/new.html.erb
<%= render 'layouts/navbar' %>

<div class="container">
  <%= simple_form_for @cocktail do |f| %>
    <%= f.input :name %>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
    <%= f.submit "add to favorites", class: "btn btn-success" %>
  <% end %>
  <%= link_to "Back to list", cocktails_path, class: "btn btn-warning" %>
</div>

<%= render 'layouts/footer' %>

app/views/cocktails/show.html.erb
<%= render 'layouts/navbar' %>

<div class="container">
  <h2><%= @cocktail.name %></h2>

  <% @cocktail.doses.each do |d| %>
    <ul>
      <li><%= "Description: #{d.description}" %></li>
      <li><%= "Ingredient : #{d.ingredient.name}" %></li>
      <li><%= link_to "Delete a dose",
              dose_path(d),
              class: "glyphicon glyphicon-trash",
              method: :delete,
              data: { confirm: "Are you sure?" } %></li>
    </ul>
    <br>
  <% end %>

  <%= link_to "Back to list", cocktails_path, class: "btn btn-success" %>
  <%= link_to "Add a dose", new_cocktail_dose_path(params[:id]), class: "btn btn-success" %>
  </div>
</div>

<%= render 'layouts/footer' %>

app/views/doses/new.html.erb
<%= render 'layouts/navbar' %>

<div class="container">
  <%= simple_form_for [@cocktail, @dose] do |f| %>
    <%= f.input :description %>
    <%= f.association :ingredient %>
    <%= f.submit "add the dose", class: "btn btn-success" %>
  <% end %>
  <%= link_to "Back to list", cocktails_path, class: "btn btn-warning" %>
</div>

<%= render 'layouts/footer' %>

app/views/layouts/_footer.html.erb
<div class="footer">

  <div class="footer-copyright">
    </i><p>MVP made at Le Wagon</p>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to image_tag("logo.png"), "/", class: "navbar-wagon-brand" %>
  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <%= link_to "About", about_pages_path, class: "navbar-wagon-item navbar-wagon-link"%>
    <%= link_to "Menu", cocktails_path, class: "navbar-wagon-item navbar-wagon-link"%>
    <!-- Profile picture with dropdown list -->
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
  </body>
</html>

app/views/pages/about.html.erb
<%= render 'layouts/navbar' %>

<div class="container">
  <div class=card-about>
    <h2>We are passionate about cocktails</h2>
    <p>At Le Wagon, coding bootcamp where we learn Web programmation, we used to have a drink after a long working day. Bored of drinking beers, we tried cocktails and discovered a new passion we want to share with all of you!</p>
  </div>
</div>

app/views/pages/menu.html.erb
<h1>Pages#menu</h1>
<p>Find me in app/views/pages/menu.html.erb</p>